version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:
        commands:
            - npm install -g @angular/cli
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - aws s3 rm s3://static-feeder-app/ --recursive
            - aws s3 cp dist/feeder/ s3://static-feeder-app/ --recursive
            - aws cloudfront create-invalidation --distribution-id 'E1WSL5LF2QJXQJ' --paths '/*'
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
